CREATE TABLE IF NOT EXISTS enemy_npc_zones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    dimension INT NOT NULL DEFAULT 0,
    zombieCount INT NOT NULL DEFAULT 3,
    respawnSec INT NOT NULL DEFAULT 60,
    points LONGTEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
