CREATE TABLE IF NOT EXISTS `farm_zones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `dx` FLOAT NOT NULL DEFAULT 10,
  `dy` FLOAT NOT NULL DEFAULT 10,
  `dz` FLOAT NOT NULL DEFAULT 5,
  `dimension` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
