"use strict";

module.exports = {
    conversionPrice: 125000,
    maxSavedPresets: 8,
    allowedVehicleTypes: [0],
    blockedModels: [
        'caddy',
        'caddy2',
        'caddy3',
        'towtruck',
        'towtruck2',
        'tractor',
        'ripley',
    ],
    workshops: [
        {
            id: 1,
            name: 'Drift Workshop LS',
            position: { x: -337.695, y: -136.863, z: 39.009 },
            radius: 3.0,
            marker: {
                type: 36,
                color: [147, 84, 255, 180],
                scale: 1.2,
            },
            blip: {
                sprite: 72,
                color: 58,
                shortRange: true,
                name: 'Drift Workshop',
            },
        },
    ],
    sliderLimits: {
        driveBiasFront: [0.0, 0.5],
        steeringLock: [0.55, 1.25],
        tractionCurveMax: [1.4, 3.0],
        tractionCurveMin: [0.9, 2.3],
        lowSpeedTractionLossMult: [0.7, 2.2],
        initialDriveForce: [0.12, 0.6],
        driveInertia: [0.7, 1.8],
        brakeBiasFront: [0.35, 0.7],
        suspensionCompDamp: [0.7, 2.2],
        suspensionReboundDamp: [0.8, 2.6],
        comShiftY: [-0.1, 0.4],
        comShiftZ: [-0.35, 0.1],
    },
    sliderSteps: {
        driveBiasFront: 0.01,
        steeringLock: 0.01,
        tractionCurveMax: 0.01,
        tractionCurveMin: 0.01,
        lowSpeedTractionLossMult: 0.01,
        initialDriveForce: 0.005,
        driveInertia: 0.01,
        brakeBiasFront: 0.01,
        suspensionCompDamp: 0.01,
        suspensionReboundDamp: 0.01,
        comShiftY: 0.01,
        comShiftZ: 0.01,
    },
};
