"use strict";

module.exports = {
    conversionPrice: 125000,
    maxSavedPresets: 8,
    allowedVehicleTypes: [0],
    blockedModels: [
        'caddy',
        'caddy2',
        'caddy3',
        'towtruck',
        'towtruck2',
        'tractor',
        'ripley',
    ],
    workshops: [
        {
            id: 1,
            name: 'Drift Workshop LS',
            position: { x: -337.695, y: -136.863, z: 39.009 },
            radius: 3.0,
            marker: {
                type: 36,
                color: [147, 84, 255, 180],
                scale: 1.2,
            },
            blip: {
                sprite: 72,
                color: 58,
                shortRange: true,
                name: 'Drift Workshop',
            },
        },
    ],
    sliderLimits: {
        driveBiasFront: [0, 100],
        steeringLock: [0, 100],
        tractionCurveMax: [0, 100],
        tractionCurveMin: [0, 100],
        lowSpeedTractionLossMult: [0, 100],
        initialDriveForce: [0, 100],
        driveInertia: [0, 100],
        brakeBiasFront: [0, 100],
        suspensionCompDamp: [0, 100],
        suspensionReboundDamp: [0, 100],
        comShiftY: [0, 100],
        comShiftZ: [0, 100],
    },
    sliderSteps: {
        driveBiasFront: 1,
        steeringLock: 1,
        tractionCurveMax: 1,
        tractionCurveMin: 1,
        lowSpeedTractionLossMult: 1,
        initialDriveForce: 1,
        driveInertia: 1,
        brakeBiasFront: 1,
        suspensionCompDamp: 1,
        suspensionReboundDamp: 1,
        comShiftY: 1,
        comShiftZ: 1,
    },
};
