"use strict";

module.exports = {
    conversionPrice: 125000,
    maxSavedPresets: 8,
    allowedVehicleTypes: [0],
    blockedModels: [
        'caddy',
        'caddy2',
        'caddy3',
        'towtruck',
        'towtruck2',
        'tractor',
        'ripley',
    ],
    workshops: [
        {
            id: 1,
            name: 'Drift Workshop LS',
            position: { x: -337.695, y: -136.863, z: 39.009 },
            radius: 3.0,
            marker: {
                type: 36,
                color: [147, 84, 255, 180],
                scale: 1.2,
            },
            blip: {
                sprite: 72,
                color: 58,
                shortRange: true,
                name: 'Drift Workshop',
            },
        },
    ],
    sliderLimits: {
        suspensionFrontStiffness: [0.65, 1.55],
        suspensionRearStiffness: [0.65, 1.55],
        suspensionFrontHeight: [-0.08, 0.1],
        suspensionRearHeight: [-0.08, 0.1],
        steeringAngle: [28, 58],
        steeringResponse: [0.6, 1.8],
        counterSteerAssist: [0, 1],
        frontGrip: [0.7, 1.2],
        rearGrip: [0.5, 1.05],
        slipFactor: [0.75, 1.35],
        torqueResponse: [0.75, 1.45],
        finalDriveBias: [0.8, 1.3],
        differentialLock: [0, 1],
        brakeBias: [0.35, 0.75],
        handbrakePower: [0.6, 1.8],
        handbrakeResponse: [0.65, 1.35],
        frontRearBalance: [-0.45, 0.45],
        bodyRotationHelp: [0, 1],
        stabilityBias: [0, 1],
        driftAssist: [0, 1],
        beginnerAssist: [0, 1],
        throttleSmoothing: [0, 1],
    },
};
